# Generated by Django 6.0 on 2025-12-30 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('college_name', models.CharField(max_length=150, verbose_name='College Name')),
                ('interested_course', models.CharField(max_length=100, verbose_name='Interested Course')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / Remarks')),
                ('enquiry_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('converted', 'Converted')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('course_name', models.CharField(max_length=100)),
                ('admission_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('total_fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Fees')),
                ('paid_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Paid Fees')),
                ('remaining_fees', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Remaining Fees')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped')], default='active', max_length=10)),
                ('lms_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='LMS Username')),
                ('certificate_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Certificate ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
    ]
